#!/bin/bash

#exit on no argument

printUsage() {
	echo "Usage: fix <binary>"
    	echo "Fixes binaries for armv7s"
}

if [ -e $1 ] 
then
		printUsage
		exit
else
	# otherwise fix the binary
        sed -i'' 's/\x00\x30\x93\xe4/\x00\x30\x93\xe5/g;s/\x00\x30\xd3\xe4/\x00\x30\xd3\xe5/g;' $1;
fi
