#!/bin/bash

printUsage() {
	echo "Usage: fix <binary>"
}

# exit on no argument
if [ -z $1 ] 
then
	printUsage
	exit
else
	# fix the binary
        sed -i'' 's/\x00\x30\x93\xe4/\x00\x30\x93\xe5/g;s/\x00\x30\xd3\xe4/\x00\x30\xd3\xe5/g;' $1;
fi
